name: tnseq_env
channels:
    - conda-forge
dependencies:
    - python=3.11
    - numpy
    - scipy
    - pandas
    - matplotlib
    - scikit-learn
    - ipykernel
    - seaborn
    - openpyxl
    - fastparquet
    - pip
    - pip:
        - tensorflow==2.16.2
        - itables